name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"  
  workflow_dispatch:          
  push:
    branches:
      - main                 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4


      - name: Generate snake-light.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: kudriavetsvaleria
          outputs: |
            output/snake-light.svg
          palette: github-light

  
      - name: Generate snake-dark.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: kudriavetsvaleria
          outputs: |
            output/snake-dark.svg
          palette: github-dark

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update snake animation"
          file_pattern: output/snake-*.svg
