name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Generate snake-dark.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: kudriavetsvaleria
          outputs: |
            output/snake-dark.svg
          color_snake: "#ff00ff"
          color_dots: "#161b22,#0e4429,#006d32,#26a641,#39d353"

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update snake animation"
          file_pattern: output/snake-dark.svg
